name: 打包isx工具

on:
  push:
    branches:
      - main

jobs:

  package:

    runs-on: ubuntu-latest

    steps:

      - name: 下载代码
        uses: actions/checkout@v4

      - name: 缓存go依赖
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: 启动go环境
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: './go.mod'

      - name: 安装项目依赖
        run: |
          go env -w GO111MODULE=auto
          go mod init isxcode.com/isxcode/isx-cli
          go install

      - name: 打包windows环境命令
        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./target/isx_windows_amd64.exe main.go

      - name: 打包linux环境命令
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./target/isx_linux_amd64 main.go

      - name: 打包macos环境命令
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ./target/isx_darwin_arm64 main.go

      - name: 安装node环境
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: isx上传到阿里云oss中
        uses: tiyee/aliyun-oss-auto-upload@v2.0.0
        with:
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-cn-shanghai
          bucket: openfly
          remote-dir: /isx/
          local-folder: ./target
          secure: true